# Generated by Django 4.2.16 on 2024-10-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dhis2Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name (e.g., 'Primary DHIS2')", max_length=100, unique=True)),
                ('api_url', models.URLField(help_text='Base URL for the DHIS2 API')),
                ('username', models.CharField(help_text='DHIS2 Username', max_length=100)),
                ('password', models.CharField(help_text='DHIS2 Password', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Use this configuration if active')),
            ],
        ),
        migrations.CreateModel(
            name='KafkaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name (e.g., 'MOH Kafka')", max_length=100, unique=True)),
                ('bootstrap_servers', models.CharField(help_text='Kafka Username', max_length=100)),
                ('security_protocol', models.CharField(help_text='Kafka Username', max_length=100)),
                ('mechanism', models.CharField(help_text='Kafka Username', max_length=100)),
                ('username', models.CharField(help_text='Kafka Username', max_length=100)),
                ('password', models.CharField(help_text='Kafka Password', max_length=100)),
                ('group_id', models.CharField(help_text='Group ID', max_length=100)),
                ('debug', models.CharField(blank=True, help_text='Kafka Password', max_length=100, null=True)),
                ('log_level', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Use this configuration if active')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_entity_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('enrollment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('event_org_unit_id', models.CharField(blank=True, max_length=50, null=True)),
                ('org_unit_code', models.CharField(blank=True, max_length=20, null=True)),
                ('program_stage_name', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('hmis_code', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('nmc_case_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nmc_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nmc_diag_name', models.CharField(blank=True, max_length=100, null=True)),
                ('case_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('case_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('case_dob', models.CharField(blank=True, max_length=100, null=True)),
                ('case_sex', models.CharField(blank=True, max_length=100, null=True)),
                ('case_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('case_loinc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('case_loinc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('case_notifier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('case_specimen_name', models.CharField(blank=True, max_length=100, null=True)),
                ('case_disease_code', models.CharField(blank=True, max_length=50, null=True)),
                ('case_rapid_test_done', models.CharField(blank=True, max_length=50, null=True)),
                ('case_notifier_designation', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_symptomatic', models.CharField(blank=True, max_length=100, null=True)),
                ('lab_notifier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lab_specimen_sent_date', models.CharField(blank=True, max_length=100, null=True)),
                ('lab_specimen_collection_date', models.CharField(blank=True, max_length=100, null=True)),
                ('lab_code', models.CharField(blank=True, max_length=100, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lab_request_pathogen', models.CharField(blank=True, max_length=100, null=True)),
                ('lab_filler_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('message_type', models.CharField(blank=True, max_length=100, null=True)),
                ('message_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('event_id', models.CharField(blank=True, max_length=50, null=True)),
                ('event_status', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('posted_to_kafka', models.BooleanField(default=False)),
                ('date_kafka_processed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hl7LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmc_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message_body', models.TextField(blank=True, null=True)),
                ('event_status', models.CharField(blank=True, max_length=50, null=True)),
                ('posted_to_kafka', models.CharField(blank=True, max_length=50, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhooks.webhookevent')),
            ],
        ),
    ]
