# Generated by Django 4.2.16 on 2024-10-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hl7labrequest',
            name='nmc_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
