# Generated by Django 4.2.16 on 2024-10-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webhookevent",
            old_name="data",
            new_name="raw_data",
        ),
        migrations.RemoveField(
            model_name="webhookevent",
            name="event_type",
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="EVENT_DATE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="EVENT_ORG_UNIT_ID",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="ORG_UNIT_CODE",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="PROGRAM_STAGE_NAME",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="TRACKED_ENTITY_ID",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="case_dob",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="case_first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="case_last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="case_loinc_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="case_loinc_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="case_phone_number_formatted",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="case_sex",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="case_specimen_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="facility_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="hmis_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="lab_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="lab_notifier_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="lab_specimen_collection_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="lab_specimen_sent_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="message_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="message_uuid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="nmc_case_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="nmc_diag_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="nmc_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="pathogen_testedfor_icd_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
