# Generated by Django 4.2.16 on 2024-10-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_rename_data_webhookevent_raw_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webhookevent",
            old_name="TRACKED_ENTITY_ID",
            new_name="tracked_entity_id",
        ),
    ]
