# Generated by Django 4.2.16 on 2024-10-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0003_rename_tracked_entity_id_webhookevent_tracked_entity_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="case_notifier_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="enrollment_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="patient_symptomatic",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
