# Generated by Django 4.2.16 on 2024-10-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0004_webhookevent_case_notifier_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="event_status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
