# Generated by Django 4.2.16 on 2024-10-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0005_webhookevent_event_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="event_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
