# Generated by Django 4.2.16 on 2024-10-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0006_webhookevent_event_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dhis2Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("base_url", models.CharField(blank=True, max_length=50, null=True)),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                ("password", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
