# Generated by Django 4.2.16 on 2024-10-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0007_dhis2config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevent',
            name='event_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
