# Generated by Django 4.2.16 on 2024-10-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0008_alter_webhookevent_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevent',
            name='event_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
