# Generated by Django 4.2.16 on 2024-10-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0009_alter_webhookevent_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhookevent',
            old_name='case_phone_number_formatted',
            new_name='case_phone_number',
        ),
        migrations.RenameField(
            model_name='webhookevent',
            old_name='pathogen_testedfor_icd_code',
            new_name='lab_request_pathogen',
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='case_disease_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='case_notifier_designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='case_rapid_test_done',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='date_kafka_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='lab_filler_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='posted_to_kafka',
            field=models.BooleanField(default=False),
        ),
    ]
