# Generated by Django 4.2.16 on 2024-10-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0010_rename_case_phone_number_formatted_webhookevent_case_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhookevent',
            old_name='EVENT_DATE',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='webhookevent',
            old_name='EVENT_ORG_UNIT_ID',
            new_name='event_org_unit_id',
        ),
        migrations.RenameField(
            model_name='webhookevent',
            old_name='ORG_UNIT_CODE',
            new_name='org_unit_code',
        ),
        migrations.RenameField(
            model_name='webhookevent',
            old_name='PROGRAM_STAGE_NAME',
            new_name='program_stage_name',
        ),
    ]
