# Generated by Django 4.2.16 on 2024-10-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0011_rename_event_date_webhookevent_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hl7LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmc_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message_body', models.TextField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhooks.webhookevent')),
            ],
        ),
    ]
