# Generated by Django 4.2.16 on 2024-10-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0012_hl7labrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hl7labrequest',
            name='event_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
