# Generated by Django 4.2.16 on 2024-10-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0013_hl7labrequest_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hl7labrequest',
            name='posted_to_kafka',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
